// Built-in food list. Values are typical label/table values PER 100 g (or 100 ml)
// and are approximate. Columns:
// [English name, Slovak name, portion EN, portion SK, grams per portion,
//  kcal, protein g, carbs g, fat g, extra search words, flags]
// Extra search words hold Slovak/English variants, plural forms and brand names so
// descriptions like "2 rožky s maslom" or "Pilos skyr" can be matched.
// Flag "w" = counts toward daily water intake (grams = ml).
const FOOD_TABLE = [
  // ---- Fruit / Ovocie ----
  ["Apple", "Jablko", "1 medium", "1 stredné", 180, 52, 0.3, 14, 0.2, "apples jablka jablk"],
  ["Banana", "Banán", "1 medium", "1 stredný", 120, 89, 1.1, 23, 0.3, "bananas banany"],
  ["Orange", "Pomaranč", "1 medium", "1 stredný", 130, 47, 0.9, 12, 0.1, "oranges pomarance"],
  ["Mandarin", "Mandarínka", "1 piece", "1 kus", 75, 53, 0.8, 13, 0.3, "mandarins tangerine klementinka mandarinky"],
  ["Grapefruit", "Grapefruit", "1/2 fruit", "1/2 plodu", 150, 42, 0.8, 11, 0.1, "grep"],
  ["Lemon", "Citrón", "1 piece", "1 kus", 60, 29, 1.1, 9, 0.3, "citron citrona"],
  ["Grapes", "Hrozno", "1 cup", "1 hrnček", 150, 69, 0.7, 18, 0.2, "grape hrozna"],
  ["Strawberries", "Jahody", "1 cup", "1 hrnček", 150, 32, 0.7, 7.7, 0.3, "strawberry jahoda jahod"],
  ["Blueberries", "Čučoriedky", "1 cup", "1 hrnček", 150, 57, 0.7, 14, 0.3, "blueberry cucoriedka"],
  ["Raspberries", "Maliny", "1 cup", "1 hrnček", 125, 52, 1.2, 12, 0.7, "raspberry malina"],
  ["Cherries", "Čerešne", "1 cup", "1 hrnček", 150, 63, 1.1, 16, 0.2, "cherry ceresna visne"],
  ["Pear", "Hruška", "1 medium", "1 stredná", 180, 57, 0.4, 15, 0.1, "pears hrusky"],
  ["Peach", "Broskyňa", "1 medium", "1 stredná", 150, 39, 0.9, 10, 0.3, "peaches broskyne"],
  ["Nectarine", "Nektárinka", "1 medium", "1 stredná", 140, 44, 1.1, 11, 0.3, "nectarines nektarinky"],
  ["Apricots", "Marhule", "3 pieces", "3 kusy", 105, 48, 1.4, 11, 0.4, "apricot marhula"],
  ["Plums", "Slivky", "3 pieces", "3 kusy", 200, 46, 0.7, 11, 0.3, "plum slivka"],
  ["Watermelon", "Vodový melón", "1 slice", "1 plátok", 280, 30, 0.6, 8, 0.2, "melon melona dyna"],
  ["Honeydew melon", "Cukrový melón", "1 slice", "1 plátok", 200, 36, 0.5, 9, 0.1, "cantaloupe galia"],
  ["Kiwi", "Kiwi", "1 piece", "1 kus", 75, 61, 1.1, 15, 0.5, "kiwis"],
  ["Pineapple", "Ananás", "1 cup", "1 hrnček", 165, 50, 0.5, 13, 0.1, "ananas"],
  ["Mango", "Mango", "1/2 fruit", "1/2 plodu", 150, 60, 0.8, 15, 0.4, "manga"],
  ["Avocado", "Avokádo", "1/2 fruit", "1/2 plodu", 100, 160, 2, 9, 15, "avocados avokada"],
  ["Pomegranate", "Granátové jablko", "1/2 fruit", "1/2 plodu", 90, 83, 1.7, 19, 1.2, "granatove"],
  ["Raisins", "Hrozienka", "a handful", "hrsť", 30, 299, 3.1, 79, 0.5, "hrozienok"],
  ["Dates", "Datle", "3 pieces", "3 kusy", 24, 282, 2.5, 75, 0.4, "date datla"],
  ["Dried apricots", "Sušené marhule", "a handful", "hrsť", 40, 241, 3.4, 63, 0.5, "susene"],
  ["Prunes", "Sušené slivky", "a handful", "hrsť", 40, 240, 2.2, 64, 0.4, ""],
  ["Fruit pouch", "Ovocná kapsička", "1 pouch", "1 kapsička", 90, 60, 0.4, 14, 0.2, "kapsicka pyre pure ovocne"],

  // ---- Vegetables / Zelenina ----
  ["Carrot", "Mrkva", "1 medium", "1 stredná", 60, 41, 0.9, 10, 0.2, "carrots mrkvy"],
  ["Cucumber", "Uhorka", "1/2 cucumber", "1/2 uhorky", 150, 15, 0.7, 3.6, 0.1, "cucumbers uhorky uhorku"],
  ["Tomato", "Paradajka", "1 medium", "1 stredná", 120, 18, 0.9, 3.9, 0.2, "tomatoes paradajky"],
  ["Cherry tomatoes", "Cherry paradajky", "10 pieces", "10 kusov", 150, 18, 0.9, 3.9, 0.2, "cherry"],
  ["Bell pepper", "Paprika", "1 medium", "1 stredná", 120, 26, 1, 6, 0.3, "pepper papriky"],
  ["Onion", "Cibuľa", "1 medium", "1 stredná", 110, 40, 1.1, 9, 0.1, "cibula onions"],
  ["Lettuce", "Hlávkový šalát", "1 bowl", "1 miska", 100, 15, 1.4, 2.9, 0.2, "hlavkovy rucola rukola"],
  ["Mixed salad", "Zeleninový šalát", "1 bowl, no dressing", "1 miska, bez dresingu", 150, 20, 1.3, 3.5, 0.2, "salad salat zeleninovy"],
  ["Broccoli", "Brokolica", "1 cup", "1 hrnček", 150, 35, 2.4, 7, 0.4, "brokolicu"],
  ["Cauliflower", "Karfiol", "1 cup", "1 hrnček", 150, 23, 1.8, 4.1, 0.5, "karfiolu"],
  ["Spinach", "Špenát", "1 portion", "1 porcia", 150, 23, 2.9, 3.6, 0.4, "spenat"],
  ["Creamed spinach", "Špenátový prívarok", "1 portion", "1 porcia", 200, 80, 3, 6, 5, "privarok spenatovy"],
  ["Zucchini", "Cuketa", "1 medium", "1 stredná", 150, 17, 1.2, 3.1, 0.3, "cukety courgette"],
  ["Green beans", "Zelená fazuľka", "1 cup", "1 hrnček", 150, 31, 1.8, 7, 0.1, "fazulka struckova"],
  ["Peas", "Hrášok", "1 cup", "1 hrnček", 150, 81, 5.4, 14, 0.4, "hrasok hrasku"],
  ["Sweet corn", "Kukurica", "1/2 can", "1/2 konzervy", 140, 86, 3.3, 19, 1.4, "corn kukurice"],
  ["Mushrooms", "Šampiňóny", "1 cup", "1 hrnček", 100, 22, 3.1, 3.3, 0.3, "sampinony huby mushroom"],
  ["Cabbage", "Kapusta", "1 cup", "1 hrnček", 100, 25, 1.3, 6, 0.1, "kapusty"],
  ["Sauerkraut", "Kyslá kapusta", "1 portion", "1 porcia", 150, 19, 0.9, 4.3, 0.1, "kysla"],
  ["Radishes", "Reďkovky", "1 bunch", "1 zväzok", 100, 16, 0.7, 3.4, 0.1, "redkovky radish"],
  ["Beetroot", "Cvikla", "1 portion", "1 porcia", 100, 43, 1.6, 10, 0.2, "cviklu beets"],
  ["Kohlrabi", "Kaleráb", "1 piece", "1 kus", 150, 27, 1.7, 6, 0.1, "kalerab"],
  ["Pickles", "Kyslé uhorky", "3 pieces", "3 kusy", 100, 12, 0.5, 2.3, 0.2, "sterilizovane cornichons"],
  ["Olives", "Olivy", "10 pieces", "10 kusov", 30, 130, 1, 5, 13, "oliv"],
  ["Frozen vegetable mix", "Zeleninová zmes", "1 cup", "1 hrnček", 150, 50, 2.5, 9, 0.4, "mrazena zmes zelenina vegetables veg"],
  ["Hummus", "Hummus", "4 tbsp", "4 lyžice", 60, 166, 7.9, 14, 9.6, "humus"],

  // ---- Potatoes / Zemiaky ----
  ["Potatoes (boiled)", "Zemiaky (varené)", "1 medium", "1 stredný", 170, 87, 1.9, 20, 0.1, "potato zemiak zemiakov"],
  ["Baked potatoes", "Pečené zemiaky", "1 portion", "1 porcia", 200, 130, 2.5, 21, 4, "americke pecene opekane"],
  ["Mashed potatoes", "Zemiaková kaša", "1 portion", "1 porcia", 200, 105, 1.9, 15, 4.2, "puree pure kasa"],
  ["French fries", "Hranolky", "medium portion", "stredná porcia", 120, 312, 3.4, 41, 15, "hranolky hranoliek fries"],
  ["Sweet potato", "Batáty", "1 medium", "1 stredný", 150, 90, 2, 21, 0.2, "batat"],
  ["Potato pancakes", "Zemiakové placky", "2 pieces", "2 kusy", 150, 230, 3, 25, 13, "placky haruľa harula"],
  ["Lokše", "Lokše", "1 piece", "1 kus", 80, 220, 4, 40, 4, "lokse loksa"],

  // ---- Dairy / Mliečne ----
  ["Milk (1.5%)", "Mlieko (polotučné)", "1 glass (250 ml)", "1 pohár (250 ml)", 250, 47, 3.3, 4.8, 1.5, "milk mlieka mliekom polotucne rajo tami"],
  ["Whole milk (3.5%)", "Plnotučné mlieko", "1 glass (250 ml)", "1 pohár (250 ml)", 250, 64, 3.3, 4.7, 3.5, "plnotucne"],
  ["Cocoa milk", "Kakao", "1 cup (250 ml)", "1 hrnček (250 ml)", 250, 80, 3.4, 11, 2, "kakaa cocoa"],
  ["Oat drink", "Ovsený nápoj", "1 glass (250 ml)", "1 pohár (250 ml)", 250, 45, 1, 6.5, 1.5, "ovseny oat alpro"],
  ["Soy drink", "Sójový nápoj", "1 glass (250 ml)", "1 pohár (250 ml)", 250, 40, 3.3, 2.5, 1.8, "sojove sojovy soy"],
  ["Plain yogurt", "Biely jogurt", "1 cup", "1 kelímok", 150, 61, 3.5, 4.7, 3.3, "biely jogurt"],
  ["Greek yogurt", "Grécky jogurt", "1 cup", "1 kelímok", 150, 125, 4.5, 4, 10, "grecky"],
  ["Skyr", "Skyr", "1 cup", "1 kelímok", 150, 63, 11, 4, 0.2, "pilos milbona skyru"],
  ["Fruit yogurt", "Ovocný jogurt", "1 cup", "1 kelímok", 150, 95, 3.2, 14, 2.8, "yogurt yoghurt jogurt jogurtu activia pilos zott ovocny"],
  ["High-protein pudding/yogurt", "Proteínový puding / jogurt", "1 cup", "1 kelímok", 200, 75, 10, 6, 1.5, "proteinovy protein ehrmann high"],
  ["Kefir", "Kefír", "1 bottle (250 ml)", "1 fľaša (250 ml)", 250, 52, 3.3, 4.5, 2, "kefir acidko zakysanka rajo"],
  ["Actimel", "Actimel", "1 bottle", "1 fľaštička", 100, 71, 2.7, 11, 1.5, ""],
  ["Cottage cheese", "Cottage syr", "1 cup", "1 kelímok", 180, 98, 11, 3.4, 4.3, "cottage"],
  ["Quark (tvaroh)", "Tvaroh", "1/2 pack", "1/2 balenia", 125, 118, 17, 3.5, 4, "tvaroh tvarohu quark"],
  ["Termix / quark dessert", "Termix", "1 cup", "1 kelímok", 90, 190, 7, 21, 8, "termix lipanek tvarohovy dezert"],
  ["Rice pudding", "Mliečna ryža", "1 cup", "1 kelímok", 200, 105, 3.3, 17, 2.8, "mliecna muller ryzovy nakyp"],
  ["Pudding", "Puding", "1 cup", "1 kelímok", 125, 110, 3, 17, 3, "puding dezert"],
  ["Cheese (Edam/Gouda)", "Syr (eidam/gouda)", "1 slice", "1 plátok", 30, 350, 26, 1, 27, "cheese cheddar edam eidam gouda syra syrom plátkový"],
  ["Mozzarella", "Mozzarella", "1/2 ball", "1/2 guľky", 60, 254, 18, 2, 19, "mozarela"],
  ["Parmesan", "Parmezán", "1 tbsp grated", "1 lyžica strúhaného", 10, 431, 38, 4, 29, "parmezan grana"],
  ["Feta / Balkan cheese", "Balkánsky syr / feta", "1 portion", "1 porcia", 50, 264, 14, 4, 21, "feta balkansky"],
  ["Bryndza", "Bryndza", "1 portion", "1 porcia", 50, 270, 15, 2, 22, "bryndzou bryndze"],
  ["Smoked cheese (oštiepok, parenica)", "Údený syr (oštiepok, parenica)", "1 portion", "1 porcia", 50, 330, 26, 1, 25, "udeny ostiepok parenica korbacik niva"],
  ["Camembert / Hermelín", "Hermelín", "1/2 piece", "1/2 kusu", 60, 300, 20, 0.5, 24, "hermelin camembert brie"],
  ["Blue cheese", "Plesňový syr", "1 portion", "1 porcia", 30, 350, 21, 0, 29, "plesnovy niva"],
  ["Processed cheese", "Tavený syr", "1 triangle", "1 trojuholník", 25, 240, 10, 4, 20, "taveny"],
  ["Cream cheese spread", "Nátierka / Lučina", "1 tbsp", "1 lyžica", 20, 250, 7, 4, 23, "lucina natierka philadelphia"],
  ["Butter", "Maslo", "1 tbsp", "1 lyžica", 14, 740, 0.7, 0.6, 82, "maslom masla"],
  ["Margarine", "Margarín / Rama", "1 tbsp", "1 lyžica", 14, 540, 0, 0.5, 60, "rama margarin palmarin"],
  ["Sour cream", "Kyslá smotana", "2 tbsp", "2 lyžice", 30, 150, 3, 4, 12, "smotana smotanou"],
  ["Whipped cream", "Šľahačka", "2 tbsp", "2 lyžice", 30, 300, 2, 3, 30, "slahacka slahackou"],
  ["Coffee creamer", "Smotana do kávy", "1 pod", "1 kelímok", 10, 118, 3, 4, 10, "smotanka"],

  // ---- Eggs / Vajcia ----
  ["Egg", "Vajce", "1 egg", "1 vajce", 55, 143, 12.6, 0.7, 9.5, "eggs vajcia vajec vajicko vajíčka boiled natvrdo varene"],
  ["Fried egg", "Volské oko", "1 egg", "1 vajce", 55, 196, 13.6, 0.8, 15, "volske fried"],
  ["Scrambled eggs", "Praženica", "from 2 eggs", "z 2 vajec", 120, 166, 11, 1.5, 13, "prazenica prazenicu scrambled"],
  ["Omelette", "Omeleta", "from 2 eggs", "z 2 vajec", 130, 154, 11, 1, 12, "omeletu omelet"],

  // ---- Bread & bakery / Pečivo ----
  ["Bread", "Chlieb", "1 slice", "1 krajec", 40, 250, 8.5, 48, 1.5, "bread chleba chlebik krajec krajce konzumny"],
  ["Wholegrain bread", "Celozrnný chlieb", "1 slice", "1 krajec", 40, 240, 9, 40, 4, "celozrnny wholemeal ražný razny"],
  ["Toast bread", "Toastový chlieb", "1 slice", "1 plátok", 25, 265, 8, 48, 4, "toastovy toast"],
  ["Bread roll (rožok)", "Rožok", "1 piece", "1 kus", 45, 285, 9, 55, 3.5, "rozky rozkov roll rolls"],
  ["Graham roll", "Grahamový rožok", "1 piece", "1 kus", 60, 260, 10, 45, 4, "grahamovy graham"],
  ["Bun / kaiser roll", "Žemľa", "1 piece", "1 kus", 55, 280, 9, 55, 2.5, "zemle zemla bun"],
  ["Baguette", "Bageta", "1/2 baguette", "1/2 bagety", 125, 270, 9, 54, 1.5, "bagetu baguette"],
  ["Croissant", "Croissant", "1 piece", "1 kus", 60, 406, 8, 45, 21, "kroasan croissanty 7days"],
  ["Pagáč", "Pagáč", "1 piece", "1 kus", 60, 380, 9, 40, 20, "pagace pagac oskvarkovy"],
  ["Strudel", "Štrúdľa / závin", "1 piece", "1 kus", 100, 280, 4, 38, 12, "strudla zavin strudel jablkova"],
  ["Sweet bun (buchta)", "Buchta", "1 piece", "1 kus", 80, 330, 7, 50, 11, "buchty buchtu"],
  ["Muffin", "Muffin", "1 piece", "1 kus", 80, 400, 5, 50, 20, "mafin muffiny"],
  ["Tortilla wrap", "Tortilla", "1 medium", "1 stredná", 60, 310, 8, 50, 8, "wrap tortilly"],
  ["Pita bread", "Pita chlieb", "1 piece", "1 kus", 60, 275, 9, 55, 1.2, "pita"],
  ["Crispbread", "Knäckebrot / Wasa", "2 pieces", "2 kusy", 20, 380, 10, 70, 4, "wasa knackebrot chrumkavy chlebik"],
  ["Rice cakes", "Ryžové chlebíčky", "3 pieces", "3 kusy", 24, 387, 8, 81, 3, "ryzove"],
  ["Pancake", "Palacinka", "1 piece", "1 kus", 70, 220, 6, 28, 9, "pancakes palacinky"],

  // ---- Grains, pasta, cereals / Prílohy, cestoviny, cereálie ----
  ["Oats", "Ovsené vločky", "40 g", "40 g", 40, 372, 13, 59, 7, "oatmeal vlocky ovsene"],
  ["Oat porridge (with milk)", "Ovsená kaša", "1 bowl", "1 miska", 250, 95, 4, 13, 3, "porridge kasa ovsena"],
  ["Semolina porridge", "Krupicová kaša", "1 bowl", "1 miska", 250, 110, 4, 17, 3, "krupicova krupica"],
  ["Rice (cooked)", "Ryža (varená)", "1 cup", "1 hrnček", 160, 130, 2.7, 28, 0.3, "rice ryza ryze ryzou"],
  ["Brown rice (cooked)", "Hnedá ryža", "1 cup", "1 hrnček", 160, 123, 2.7, 26, 1, "hneda natural"],
  ["Pasta (cooked)", "Cestoviny (varené)", "1 plate", "1 tanier", 200, 157, 5.8, 31, 0.9, "pasta cestovin spaghetti spagety penne noodles rezance"],
  ["Wholegrain pasta (cooked)", "Celozrnné cestoviny", "1 plate", "1 tanier", 200, 149, 6, 30, 1.7, "celozrnne"],
  ["Couscous (cooked)", "Kuskus", "1 cup", "1 hrnček", 150, 112, 3.8, 23, 0.2, "kuskus couscous"],
  ["Bulgur (cooked)", "Bulgur", "1 cup", "1 hrnček", 150, 83, 3, 19, 0.2, ""],
  ["Quinoa (cooked)", "Quinoa", "1 cup", "1 hrnček", 150, 120, 4.4, 21, 1.9, "kinoa"],
  ["Gnocchi", "Gnocchi", "1 portion", "1 porcia", 200, 150, 3.5, 33, 0.3, "noky"],
  ["Bread dumpling (knedľa)", "Knedľa", "3 slices", "3 plátky", 120, 220, 6, 45, 1.5, "knedla knedle knedlik"],
  ["Cornflakes", "Cornflakes", "1 bowl", "1 miska", 30, 378, 7, 84, 0.9, "cereal lupienky"],
  ["Muesli", "Müsli", "1 bowl", "1 miska", 50, 365, 10, 62, 7, "musli muesli crownfield"],
  ["Granola (crunchy muesli)", "Chrumkavé müsli", "1 bowl", "1 miska", 50, 450, 8, 63, 18, "granola chrumkave"],
  ["Chocolate cereal", "Čokoládové cereálie", "1 bowl", "1 miska", 30, 390, 8, 78, 4, "cerealie cokoladove nesquik chocapic"],

  // ---- Meat / Mäso ----
  ["Chicken breast", "Kuracie prsia", "1 portion", "1 porcia", 150, 165, 31, 0, 3.6, "chicken kuracie kura kuraci prsia prsnik"],
  ["Chicken thigh", "Kuracie stehno", "1 piece", "1 kus", 150, 209, 26, 0, 11, "stehna stehno thighs"],
  ["Chicken wings", "Kuracie krídla", "5 pieces", "5 kusov", 150, 250, 24, 0, 17, "kridla kridielka wings"],
  ["Chicken nuggets", "Kuracie nugetky", "6 pieces", "6 kusov", 100, 296, 15, 18, 18, "nugety nuggets nugetky"],
  ["Breaded chicken schnitzel", "Vyprážaný kurací rezeň", "1 piece", "1 kus", 150, 245, 19, 12, 13, "kuraci rezen vyprazany"],
  ["Breaded pork schnitzel", "Vyprážaný bravčový rezeň", "1 piece", "1 kus", 150, 270, 17, 14, 16, "rezen schnitzel vyprazany bravcovy"],
  ["Turkey breast", "Morčacie prsia", "1 portion", "1 porcia", 150, 135, 29, 0, 1.5, "morcacie morka turkey"],
  ["Turkey ham", "Morčacia šunka", "2 slices", "2 plátky", 30, 105, 18, 2, 2.5, "morcacia"],
  ["Ham", "Šunka", "2 slices", "2 plátky", 30, 120, 18, 1.5, 4.5, "sunka sunkou sunky ham"],
  ["Salami", "Saláma", "3 slices", "3 plátky", 30, 420, 22, 1, 37, "salama salamy salami inovecka"],
  ["Frankfurters", "Párky", "1 pair", "1 pár", 100, 290, 12, 2, 26, "parky parok sausage"],
  ["Klobása", "Klobása", "1 piece", "1 kus", 100, 330, 14, 2, 30, "klobasa klobasu"],
  ["Grill sausage (špekáčik)", "Špekáčik", "1 piece", "1 kus", 100, 300, 12, 2, 27, "spekacik spekacky"],
  ["Bacon", "Slanina", "3 slices", "3 plátky", 30, 420, 17, 0, 39, "slanina slaninou bacon"],
  ["Pork", "Bravčové mäso", "1 portion", "1 porcia", 150, 250, 26, 0, 16, "pork bravcove kare"],
  ["Pork neck", "Bravčová krkovička", "1 portion", "1 porcia", 150, 280, 24, 0, 20, "krkovicka"],
  ["Beef", "Hovädzie mäso", "1 portion", "1 porcia", 150, 250, 26, 0, 15, "beef hovadzie steak"],
  ["Minced meat (cooked)", "Mleté mäso", "1 portion", "1 porcia", 100, 250, 25, 0, 17, "mlete minced"],
  ["Meatballs / fašírka", "Fašírky", "2 pieces", "2 kusy", 150, 250, 15, 10, 16, "fasirka fasirky karbonatky meatballs"],
  ["Roast duck", "Pečená kačka", "1 portion", "1 porcia", 150, 337, 19, 0, 28, "kacka kacica duck"],
  ["Pâté", "Paštéta", "1/2 can", "1/2 konzervy", 50, 290, 12, 3, 26, "pasteta"],

  // ---- Fish / Ryby ----
  ["Tuna in water", "Tuniak vo vlastnej šťave", "1 can", "1 konzerva", 120, 116, 26, 0, 1, "tuniak tuniaka tuna"],
  ["Tuna in oil", "Tuniak v oleji", "1 can", "1 konzerva", 120, 190, 26, 0, 9, "oleji"],
  ["Salmon", "Losos", "1 fillet", "1 filet", 125, 208, 20, 0, 13, "losos lososa"],
  ["Trout", "Pstruh", "1 fillet", "1 filet", 150, 150, 21, 0, 6.6, "pstruh pstruha"],
  ["Cod / pollock", "Treska", "1 fillet", "1 filet", 150, 90, 20, 0, 0.8, "treska tresky aljasska cod"],
  ["Fish fingers", "Rybie prsty", "5 pieces", "5 kusov", 125, 230, 13, 20, 11, "rybie prsty"],
  ["Sardines (canned)", "Sardinky", "1 can", "1 konzerva", 90, 208, 25, 0, 11, "sardinky sardines"],
  ["Smoked mackerel", "Údená makrela", "1/2 fish", "1/2 ryby", 100, 305, 19, 0, 25, "makrela makrely"],
  ["Shrimp", "Krevety", "1 portion", "1 porcia", 100, 99, 24, 0.2, 0.3, "krevety prawns"],

  // ---- Legumes, nuts, seeds / Strukoviny, orechy ----
  ["Beans (canned)", "Fazuľa (konzerva)", "1/2 can", "1/2 konzervy", 200, 90, 6, 14, 0.5, "beans fazula fazule"],
  ["Baked beans", "Fazuľa v paradajkovej omáčke", "1/2 can", "1/2 konzervy", 200, 85, 5, 13, 0.4, "baked"],
  ["Lentils (cooked)", "Šošovica (varená)", "1 cup", "1 hrnček", 200, 116, 9, 20, 0.4, "sosovica sosovicu lentils"],
  ["Chickpeas (cooked)", "Cícer", "1 cup", "1 hrnček", 150, 164, 9, 27, 2.6, "cicer chickpea"],
  ["Tofu", "Tofu", "1 portion", "1 porcia", 100, 76, 8, 1.9, 4.8, ""],
  ["Almonds", "Mandle", "a handful", "hrsť", 28, 579, 21, 22, 50, "almond mandli"],
  ["Walnuts", "Vlašské orechy", "a handful", "hrsť", 28, 654, 15, 14, 65, "orechy orechov walnut nuts"],
  ["Peanuts", "Arašidy", "a handful", "hrsť", 28, 590, 26, 16, 50, "arasidy peanut burske"],
  ["Cashews", "Kešu", "a handful", "hrsť", 28, 553, 18, 30, 44, "kesu cashew"],
  ["Hazelnuts", "Lieskové orechy", "a handful", "hrsť", 28, 628, 15, 17, 61, "lieskove"],
  ["Pistachios", "Pistácie", "a handful", "hrsť", 28, 560, 20, 28, 45, "pistacie"],
  ["Sunflower seeds", "Slnečnicové semienka", "2 tbsp", "2 lyžice", 20, 584, 21, 20, 51, "slnecnicove semienka"],
  ["Chia seeds", "Chia semienka", "1 tbsp", "1 lyžica", 12, 486, 17, 42, 31, "chia"],
  ["Peanut butter", "Arašidové maslo", "1 tbsp", "1 lyžica", 16, 588, 25, 20, 50, "arasidove"],
  ["Nutella", "Nutella", "1 tbsp", "1 lyžica", 20, 539, 6.3, 57, 31, "nutelou nutely"],

  // ---- Sweets & snacks / Sladkosti a snacky ----
  ["Honey", "Med", "1 tsp", "1 lyžička", 7, 304, 0.3, 82, 0, "medom"],
  ["Jam", "Džem", "1 tbsp", "1 lyžica", 20, 250, 0.4, 62, 0.1, "dzem lekvar dzemom"],
  ["Sugar", "Cukor", "1 tsp", "1 lyžička", 5, 400, 0, 100, 0, "cukru cukrom"],
  ["Dark chocolate", "Horká čokoláda", "2 squares", "2 kocky", 20, 580, 7.8, 40, 43, "horka"],
  ["Milk chocolate", "Mliečna čokoláda", "1 bar (100 g)", "1 tabuľka (100 g)", 100, 535, 7.7, 59, 30, "cokolada cokolady chocolate fin carre"],
  ["Milka", "Milka", "1 bar (100 g)", "1 tabuľka (100 g)", 100, 539, 6.3, 58, 31, ""],
  ["Snickers", "Snickers", "1 bar", "1 tyčinka", 50, 488, 8.6, 60, 24, ""],
  ["Mars", "Mars", "1 bar", "1 tyčinka", 51, 449, 4, 70, 17, ""],
  ["Twix", "Twix", "1 pack", "1 balenie", 50, 495, 4.5, 65, 24, ""],
  ["KitKat", "KitKat", "1 bar", "1 tyčinka", 42, 518, 7.3, 58, 27, "kit kat"],
  ["Bounty", "Bounty", "1 pack", "1 balenie", 57, 487, 3.7, 59, 26, ""],
  ["Kinder Bueno", "Kinder Bueno", "1 pack", "1 balenie", 43, 572, 8.6, 50, 37, "bueno"],
  ["Kinder chocolate", "Kinder čokoláda", "1 bar", "1 tyčinka", 12.5, 566, 8.7, 53, 35, "kinder"],
  ["Kinder Milk-Slice", "Kinder Mliečny rez", "1 piece", "1 kus", 28, 421, 8, 31, 28, "mliecny rez milchschnitte"],
  ["Kinder Pingui", "Kinder Pingui", "1 piece", "1 kus", 30, 445, 7.5, 32, 31, "pingui"],
  ["Horalky", "Horalky", "1 piece", "1 kus", 50, 520, 7.6, 59, 28, "horalka sedita"],
  ["Tatranka", "Tatranka", "1 piece", "1 kus", 47, 530, 6.5, 60, 29, "tatranky"],
  ["Mila wafer", "Mila", "1 piece", "1 kus", 50, 525, 5, 60, 29, "mila"],
  ["Fidorka", "Fidorka", "1 piece", "1 kus", 30, 520, 6, 56, 30, ""],
  ["Deli bar", "Deli tyčinka", "1 bar", "1 tyčinka", 35, 500, 8, 52, 29, "deli figaro"],
  ["Bebe Dobré ráno", "BeBe Dobré ráno", "1 pack", "1 balenie", 50, 440, 7.5, 69, 14, "bebe dobre rano"],
  ["Oreo", "Oreo", "3 cookies", "3 sušienky", 33, 480, 5, 69, 20, ""],
  ["Wafers", "Oblátky", "3 pieces", "3 kusy", 30, 520, 6, 60, 28, "oblatky oblatka wafer tastino kavenky"],
  ["Biscuits / cookies", "Sušienky / keksy", "3 pieces", "3 kusy", 30, 480, 6.5, 70, 20, "susienky susienka keksy cookie cookies biscuits maslove"],
  ["Chocolate bar (other)", "Čokoládová tyčinka", "1 bar", "1 tyčinka", 45, 490, 6, 60, 25, "tycinka cokoladova"],
  ["Granola bar", "Müsli tyčinka", "1 bar", "1 tyčinka", 25, 440, 6, 65, 17, "musli tycinka corny"],
  ["Protein bar", "Proteínová tyčinka", "1 bar", "1 tyčinka", 60, 370, 33, 30, 12, "proteinova protein"],
  ["Chips", "Čipsy", "small bag", "malé balenie", 30, 536, 6.5, 53, 34, "cipsy crisps chips lays slovakia bohemia"],
  ["Pringles", "Pringles", "1/5 can", "1/5 dózy", 30, 534, 4.9, 49, 34, ""],
  ["Peanut puffs (Chrumky)", "Chrumky", "small bag", "malé balenie", 30, 510, 12, 55, 27, "chrumky arasidove"],
  ["Salted sticks / pretzels", "Slané tyčinky", "a handful", "hrsť", 30, 380, 10, 76, 3.5, "slane tycinky pretzel preclik"],
  ["Bake Rolls", "Bake Rolls", "a handful", "hrsť", 30, 430, 11, 68, 12, "bake rolls"],
  ["Popcorn", "Popcorn", "1 bowl", "1 miska", 30, 480, 9, 58, 24, "pukance"],
  ["Gummy bears", "Gumené cukríky", "a handful", "hrsť", 25, 343, 6.9, 77, 0.5, "haribo gumove cukriky medvedik"],
  ["Ice cream", "Zmrzlina", "2 scoops", "2 kopčeky", 100, 210, 3.5, 24, 11, "zmrzliny icecream"],
  ["Ice cream bar", "Nanuk", "1 piece", "1 kus", 70, 280, 3.5, 28, 17, "nanuk magnum"],
  ["Cake", "Koláč / zákusok", "1 piece", "1 kus", 100, 350, 5, 45, 17, "kolac zakusok torta cake tvarohovy makovy orechovy"],
  ["Donut", "Šiška / donut", "1 piece", "1 kus", 70, 390, 6, 45, 20, "siska donut doughnut krapn"],

  // ---- Drinks / Nápoje ----
  ["Water", "Voda", "1 glass (250 ml)", "1 pohár (250 ml)", 250, 0, 0, 0, 0, "voda vody vodu water", "w"],
  ["Mineral water", "Minerálka", "1 bottle (500 ml)", "1 fľaša (500 ml)", 500, 0, 0, 0, 0, "mineralka mineralna rajec budis", "w"],
  ["Coffee (black)", "Káva (čierna)", "1 cup", "1 šálka", 200, 1, 0.1, 0, 0, "coffee kava kavu", "w"],
  ["Espresso", "Espresso", "1 shot", "1 šálka", 30, 2, 0.1, 0.3, 0, "presso", "w"],
  ["Coffee with milk", "Káva s mliekom", "1 cup", "1 šálka", 200, 20, 1, 2, 0.7, "biela", "w"],
  ["Cappuccino", "Cappuccino", "1 cup", "1 šálka", 200, 55, 2.8, 4.5, 2.8, "kapucino", "w"],
  ["Latte", "Latte", "1 glass", "1 pohár", 300, 55, 3, 4.7, 2.6, "latte macchiato flat white", "w"],
  ["Tea", "Čaj", "1 cup", "1 šálka", 250, 1, 0, 0.2, 0, "caj tea bylinkovy ovocny", "w"],
  ["Tea with sugar", "Čaj s cukrom", "1 cup", "1 šálka", 250, 14, 0, 3.5, 0, "sladeny", "w"],
  ["Hot chocolate", "Horúca čokoláda", "1 cup", "1 šálka", 250, 80, 3, 12, 2.4, "horuca"],
  ["Orange juice", "Pomarančový džús", "1 glass", "1 pohár", 250, 45, 0.7, 10, 0.2, "juice dzus pomarancovy"],
  ["Apple juice", "Jablkový džús", "1 glass", "1 pohár", 250, 46, 0.1, 11, 0.1, "jablkovy mus"],
  ["Smoothie", "Smoothie", "1 bottle", "1 fľaša", 250, 55, 0.6, 12, 0.3, "smoothies"],
  ["Cola", "Cola", "1 can (330 ml)", "1 plechovka (330 ml)", 330, 42, 0, 10.6, 0, "coca pepsi soda"],
  ["Cola Zero / light", "Cola Zero / light", "1 can (330 ml)", "1 plechovka (330 ml)", 330, 0.3, 0, 0, 0, "zero light diet"],
  ["Kofola", "Kofola", "1 bottle (500 ml)", "1 fľaša (500 ml)", 500, 32, 0, 7.8, 0, "kofoly kofolu"],
  ["Vinea", "Vinea", "1 bottle (250 ml)", "1 fľaša (250 ml)", 250, 42, 0, 10, 0, "vinea"],
  ["Lemonade (Fanta, Sprite)", "Limonáda (Fanta, Sprite)", "1 can (330 ml)", "1 plechovka (330 ml)", 330, 38, 0, 9.5, 0, "limonada fanta sprite mirinda"],
  ["Iced tea", "Ľadový čaj", "1 bottle (500 ml)", "1 fľaša (500 ml)", 500, 24, 0, 6, 0, "ice nestea lipton ladovy"],
  ["Energy drink", "Energetický nápoj", "1 can (250 ml)", "1 plechovka (250 ml)", 250, 45, 0, 11, 0, "red bull monster energetak energy"],
  ["Beer", "Pivo", "0.5 l", "0,5 l", 500, 43, 0.5, 3.6, 0, "piva beer desitka dvanastka"],
  ["Non-alcoholic beer", "Nealko pivo", "0.5 l", "0,5 l", 500, 25, 0.3, 5, 0, "nealko birell"],
  ["Radler", "Radler", "0.5 l", "0,5 l", 500, 40, 0.3, 8, 0, "radler"],
  ["Wine", "Víno", "1 glass (150 ml)", "1 pohár (150 ml)", 150, 83, 0.1, 2.6, 0, "vino wine strik"],
  ["Spirits (vodka, rum…)", "Tvrdý alkohol (vodka, borovička…)", "1 shot (40 ml)", "1 poldeci (40 ml)", 40, 231, 0, 0, 0, "vodka borovicka slivovica rum whisky poldeci tvrdy panak"],
  ["Protein shake", "Proteínový nápoj", "1 scoop in water", "1 odmerka vo vode", 30, 380, 75, 8, 6, "srvatkovy protein whey shake"],

  // ---- Meals / Jedlá ----
  ["Pizza", "Pizza", "1 slice", "1 kúsok", 110, 260, 11, 32, 10, "pizze pizzu"],
  ["Pizza (whole)", "Celá pizza", "1 pizza (32 cm)", "1 pizza (32 cm)", 450, 250, 11, 31, 9, "cela whole"],
  ["Frozen pizza", "Mrazená pizza", "1 pizza", "1 pizza", 340, 250, 10, 26, 11, "mrazena ristorante feliciana"],
  ["Burger", "Burger", "1 regular", "1 bežný", 200, 250, 13, 24, 11, "hamburger burgre"],
  ["Cheeseburger", "Cheeseburger", "1 piece", "1 kus", 115, 264, 15, 27, 11, "cheesburger"],
  ["Big Mac", "Big Mac", "1 piece", "1 kus", 219, 257, 13, 20, 14, "bigmac mcdonalds"],
  ["Kebab / gyros", "Kebab / gyros", "1 wrap", "1 kus", 350, 200, 11, 19, 9, "gyros doner kebap"],
  ["Hot dog", "Hot dog", "1 piece", "1 kus", 150, 250, 9, 24, 13, "hotdog"],
  ["Sandwich", "Sendvič", "1 piece", "1 kus", 150, 220, 11, 26, 8, "sendvic bageta obložená"],
  ["Toasted sandwich", "Hrianka so šunkou a syrom", "1 piece", "1 kus", 120, 260, 14, 25, 12, "hrianka toasty"],
  ["Open sandwich (chlebíček)", "Chlebíček", "1 piece", "1 kus", 80, 220, 6, 18, 14, "chlebicek chlebicky"],
  ["Burrito", "Burrito", "1 piece", "1 kus", 300, 200, 8, 24, 8, "burito"],
  ["Sushi", "Sushi", "8 pieces", "8 kusov", 200, 150, 6, 27, 2, "suši"],
  ["Instant noodles", "Instantné rezance", "1 pack", "1 balenie", 70, 440, 9, 60, 17, "instantne vifon ramen"],
  ["Chinese chicken with rice", "Čína s ryžou", "1 box", "1 box", 400, 150, 8, 18, 5, "cina ciny asia wok"],
  ["Caesar salad", "Šalát Caesar", "1 bowl", "1 miska", 300, 120, 9, 6, 7, "caesar cezar"],
  ["Potato salad", "Zemiakový šalát", "1 portion", "1 porcia", 200, 150, 2, 13, 10, "zemiakovy"],
  ["Soup", "Polievka", "1 bowl", "1 tanier", 300, 50, 2, 6, 2, "polievka polievku soup"],
  ["Chicken noodle soup", "Slepačí vývar s rezancami", "1 bowl", "1 tanier", 350, 35, 2.5, 3.5, 1.3, "vyvar slepaci kuraci"],
  ["Kapustnica", "Kapustnica", "1 bowl", "1 tanier", 350, 60, 3, 4, 4, "kapustnica kapustnicu"],
  ["Goulash soup", "Gulášová polievka", "1 bowl", "1 tanier", 350, 70, 4.5, 5, 3.8, "gulasova"],
  ["Tomato soup", "Paradajková polievka", "1 bowl", "1 tanier", 300, 45, 1, 7, 1.5, "paradajkova"],
  ["Garlic soup", "Cesnaková polievka", "1 bowl", "1 tanier", 300, 60, 2, 6, 3, "cesnakova cesnacka"],
  ["Bean soup", "Fazuľová polievka", "1 bowl", "1 tanier", 350, 80, 4, 9, 3, "fazulova"],
  ["Bryndzové halušky", "Bryndzové halušky", "1 plate", "1 tanier", 350, 200, 6, 25, 8.5, "halusky"],
  ["Strapačky", "Strapačky s kapustou", "1 plate", "1 tanier", 350, 170, 5, 28, 4, "strapacky"],
  ["Pierogi (bryndza)", "Pirohy", "1 plate", "1 tanier", 300, 220, 7, 30, 8, "pirohy pierogi"],
  ["Goulash", "Guláš", "1 plate", "1 tanier", 300, 140, 11, 5, 8, "gulas gulasu goulash"],
  ["Segedin goulash", "Segedínsky guláš", "1 plate", "1 tanier", 300, 120, 8, 5, 7, "segedinsky segedin"],
  ["Beef in cream sauce (sviečková)", "Sviečková na smotane", "1 plate", "1 tanier", 400, 170, 8, 18, 7, "sviečková sviečkova sviekova"],
  ["Schnitzel with potato salad", "Rezeň so zemiakovým šalátom", "1 plate", "1 tanier", 400, 250, 10, 17, 16, "rezen"],
  ["Fried cheese", "Vyprážaný syr", "1 piece", "1 kus", 120, 350, 20, 15, 24, "vyprazany syr"],
  ["Spaghetti bolognese", "Špagety bolonské", "1 plate", "1 tanier", 350, 157, 8, 20, 5, "bolognese bolonske"],
  ["Spaghetti carbonara", "Špagety carbonara", "1 plate", "1 tanier", 350, 190, 8, 20, 9, "carbonara karbonara"],
  ["Lasagne", "Lasagne", "1 portion", "1 porcia", 350, 150, 8, 14, 7, "lasagna lazane"],
  ["Risotto", "Rizoto", "1 plate", "1 tanier", 350, 140, 5, 20, 4.5, "rizoto"],
  ["Chicken with rice", "Kuracie s ryžou", "1 plate", "1 tanier", 400, 140, 11, 17, 3, ""],
  ["Stuffed peppers", "Plnená paprika", "1 plate", "1 tanier", 400, 110, 6, 11, 4.5, "plnena"],
  ["Lentil stew", "Šošovicový prívarok", "1 plate", "1 tanier", 300, 110, 6, 15, 3, "sosovicovy"],
  ["Steamed buns (parené buchty)", "Parené buchty", "2 pieces", "2 kusy", 200, 260, 6, 45, 6, "parene"],
  ["Šúľance", "Šúľance", "1 plate", "1 tanier", 300, 250, 6, 40, 7, "sulance"],
  ["Fruit dumplings", "Ovocné knedle", "4 pieces", "4 kusy", 250, 210, 5, 40, 3, "ovocne knedle"],

  // ---- Sauces / Omáčky ----
  ["Ketchup", "Kečup", "1 tbsp", "1 lyžica", 15, 112, 1.2, 26, 0.1, "kecup"],
  ["Mayonnaise", "Majonéza", "1 tbsp", "1 lyžica", 15, 680, 1, 1, 75, "majoneza mayo"],
  ["Mustard", "Horčica", "1 tsp", "1 lyžička", 10, 80, 4.5, 6, 4, "horcica"],
  ["Tartar sauce", "Tatárska omáčka", "1 tbsp", "1 lyžica", 20, 400, 1, 6, 40, "tatarska"],
  ["Salad dressing", "Dresing", "2 tbsp", "2 lyžice", 30, 250, 1, 10, 23, "dresing dressing"],
  ["Pesto", "Pesto", "2 tbsp", "2 lyžice", 30, 450, 5, 5, 45, ""],
  ["Tomato sauce (passata)", "Paradajková omáčka", "1/2 cup", "1/2 hrnčeka", 100, 35, 1.5, 6, 0.3, "passata omacka"],
  ["Soy sauce", "Sójová omáčka", "1 tbsp", "1 lyžica", 15, 53, 8, 4.9, 0.6, "sojova"],
  ["Olive oil", "Olivový olej", "1 tbsp", "1 lyžica", 13, 884, 0, 0, 100, "oil olej oleja slnecnicovy"],
];

const FOODS = FOOD_TABLE.map(([en, sk, pEn, pSk, g, kcal, p, c, f, aliases, flags]) => ({
  name: { en, sk },
  portion: { en: pEn, sk: pSk },
  g,
  per100: { kcal, p, c, f },
  kcal: Math.round((kcal * g) / 100), // per portion
  water: flags === "w",
  liquid: flags === "w" || /\bml\b|\d l\b/.test(pEn), // shown in ml instead of g
  aliases: aliases || "",
}));

// Very easy recipes, used for recommendations when you still have calories left.
// meals: which parts of the day the recipe suits. p/c/f = grams of protein/carbs/fat.
function R(kcal, p, c, f, mins, meals, en, sk) { return { kcal, p, c, f, mins, meals, en, sk }; }

const RECIPES = [
  R(330, 9, 45, 10, 3, ["breakfast", "snack"],
    { name: "Banana & peanut butter toast", ingredients: ["1 slice wholegrain bread", "1 tbsp peanut butter", "1 banana"], steps: "Toast the bread, spread peanut butter, top with banana slices." },
    { name: "Toast s arašidovým maslom a banánom", ingredients: ["1 krajec celozrnného chleba", "1 lyžica arašidového masla", "1 banán"], steps: "Opeč chlieb, natri arašidovým maslom a navrch daj plátky banánu." }),
  R(230, 12, 24, 9, 2, ["breakfast", "snack"],
    { name: "Greek yogurt with honey & berries", ingredients: ["150 g Greek yogurt", "1/2 cup berries", "1 tsp honey"], steps: "Put yogurt in a bowl, add berries and drizzle with honey." },
    { name: "Grécky jogurt s medom a ovocím", ingredients: ["150 g gréckeho jogurtu", "hrsť bobuľového ovocia", "1 lyžička medu"], steps: "Daj jogurt do misky, pridaj ovocie a polej medom." }),
  R(300, 11, 50, 5, 5, ["breakfast"],
    { name: "Overnight oats", ingredients: ["40 g oats", "150 ml milk", "1/2 banana", "1 tsp honey"], steps: "Mix oats and milk in a jar and leave in the fridge overnight. Top with banana and honey." },
    { name: "Ovsené vločky cez noc", ingredients: ["40 g ovsených vločiek", "150 ml mlieka", "1/2 banánu", "1 lyžička medu"], steps: "Zmiešaj vločky s mliekom v pohári a nechaj cez noc v chladničke. Navrch daj banán a med." }),
  R(290, 16, 20, 15, 7, ["breakfast", "lunch", "dinner"],
    { name: "Scrambled eggs on toast", ingredients: ["2 eggs", "1 tsp butter", "1 slice bread", "pinch of salt"], steps: "Whisk the eggs and cook them in butter on low heat while stirring. Serve on toast." },
    { name: "Praženica na chlebe", ingredients: ["2 vajcia", "1 lyžička masla", "1 krajec chleba", "štipka soli"], steps: "Rozšľahaj vajcia, na masle ich pomaly miešaj na miernom ohni, podávaj na chlebe." }),
  R(156, 13, 1, 10, 10, ["breakfast", "snack"],
    { name: "Two boiled eggs", ingredients: ["2 eggs", "salt, pepper"], steps: "Boil the eggs for 8–10 minutes, cool them in cold water, peel and season." },
    { name: "Dve vajcia natvrdo", ingredients: ["2 vajcia", "soľ, korenie"], steps: "Vajcia var 8–10 minút, schlaď v studenej vode, ošúp a okoreň." }),
  R(260, 7, 31, 14, 1, ["snack"],
    { name: "Apple with a handful of almonds", ingredients: ["1 apple", "28 g almonds"], steps: "Slice the apple and eat it with the almonds." },
    { name: "Jablko s hrsťou mandlí", ingredients: ["1 jablko", "hrsť mandlí (28 g)"], steps: "Nakrájaj jablko a jedz s mandľami." }),
  R(140, 14, 7, 6, 2, ["snack", "breakfast"],
    { name: "Cottage cheese & cucumber", ingredients: ["125 g cottage cheese", "1/2 cucumber", "salt, pepper, chives"], steps: "Chop the cucumber, mix it with the cottage cheese and season." },
    { name: "Cottage s uhorkou", ingredients: ["125 g cottage syra", "1/2 uhorky", "soľ, korenie, pažítka"], steps: "Nakrájaj uhorku, zmiešaj s cottage syrom a dochuť." }),
  R(340, 20, 39, 11, 3, ["breakfast", "lunch", "snack"],
    { name: "Ham & cheese sandwich", ingredients: ["2 slices bread", "2 slices ham", "1 slice cheese", "a few lettuce leaves"], steps: "Put the ham, cheese and lettuce between the bread slices." },
    { name: "Chlieb so šunkou a syrom", ingredients: ["2 krajce chleba", "2 plátky šunky", "1 plátok syra", "pár listov šalátu"], steps: "Medzi krajce chleba daj šunku, syr a šalát." }),
  R(350, 37, 35, 7, 5, ["lunch", "dinner"],
    { name: "Tuna wrap", ingredients: ["1 tortilla wrap", "1 can tuna", "1 tbsp light mayo or yogurt", "lettuce, tomato"], steps: "Mix the tuna with mayo or yogurt, spread it on the wrap, add the veg and roll it up." },
    { name: "Tortilla s tuniakom", ingredients: ["1 tortilla", "1 konzerva tuniaka", "1 lyžica jogurtu alebo light majonézy", "šalát, paradajka"], steps: "Zmiešaj tuniaka s jogurtom, natri na tortillu, pridaj zeleninu a zaroluj." }),
  R(440, 42, 61, 3, 12, ["lunch", "dinner"],
    { name: "Tuna pasta", ingredients: ["80 g dry pasta", "1 can tuna", "3 tbsp tomato sauce", "pinch of oregano"], steps: "Cook the pasta and drain it. Stir in the tuna and tomato sauce and heat for 1 minute." },
    { name: "Cestoviny s tuniakom", ingredients: ["80 g suchých cestovín", "1 konzerva tuniaka", "3 lyžice paradajkovej omáčky", "štipka oregana"], steps: "Uvar cestoviny, sceď, vmiešaj tuniaka a omáčku, 1 minútu prehrej." }),
  R(410, 37, 51, 5, 15, ["lunch", "dinner"],
    { name: "Chicken & rice bowl", ingredients: ["120 g chicken breast", "1 cup cooked rice", "handful of frozen veg", "1 tsp soy sauce"], steps: "Cut the chicken into strips and pan-fry for 6–8 min. Add the frozen veg for 3 min, then serve over rice with soy sauce." },
    { name: "Kuracie s ryžou", ingredients: ["120 g kuracích pŕs", "1 hrnček varenej ryže", "hrsť mrazenej zeleniny", "1 lyžička sójovej omáčky"], steps: "Kuracie nakrájaj na pásiky a opeč 6–8 min, pridaj zeleninu na 3 min, podávaj s ryžou a sójovou omáčkou." }),
  R(330, 14, 61, 1, 10, ["lunch", "dinner"],
    { name: "Microwave jacket potato with beans", ingredients: ["1 medium potato", "1/2 can baked beans", "a little grated cheese (optional)"], steps: "Prick the potato and microwave it for 7–8 min, turning once. Split it and top with warm beans (and cheese)." },
    { name: "Zemiak z mikrovlnky s fazuľou", ingredients: ["1 stredný zemiak", "1/2 konzervy fazule v paradajkovej omáčke", "trochu syra (nepovinné)"], steps: "Zemiak popichaj a daj na 7–8 min do mikrovlnky (raz otoč). Rozkroj a navrch daj teplú fazuľu (a syr)." }),
  R(300, 21, 1, 22, 6, ["breakfast", "lunch", "dinner"],
    { name: "Cheese omelette", ingredients: ["2 eggs", "30 g grated cheese", "1 tsp butter"], steps: "Whisk the eggs, pour them into a buttered pan, sprinkle the cheese and fold once set." },
    { name: "Syrová omeleta", ingredients: ["2 vajcia", "30 g strúhaného syra", "1 lyžička masla"], steps: "Rozšľahaj vajcia, vylej na panvicu s maslom, posyp syrom a keď stuhne, prelož." }),
  R(240, 13, 10, 17, 4, ["lunch", "dinner", "snack"],
    { name: "Caprese salad", ingredients: ["2 tomatoes", "60 g mozzarella", "1 tsp olive oil", "basil, salt"], steps: "Slice the tomatoes and mozzarella, layer them, drizzle with oil and season." },
    { name: "Šalát caprese", ingredients: ["2 paradajky", "60 g mozzarelly", "1 lyžička olivového oleja", "bazalka, soľ"], steps: "Nakrájaj paradajky a mozzarellu, poukladaj, pokvapkaj olejom a osoľ." }),
  R(270, 16, 42, 2, 12, ["lunch", "dinner"],
    { name: "Quick bean & veg soup", ingredients: ["1/2 can mixed beans", "1 cup frozen veg", "400 ml stock (cube)", "pinch of paprika"], steps: "Put everything in a pot and simmer for 10 minutes." },
    { name: "Rýchla fazuľová polievka", ingredients: ["1/2 konzervy fazule", "hrnček mrazenej zeleniny", "400 ml vývaru (z kocky)", "štipka papriky"], steps: "Všetko daj do hrnca a 10 minút povar." }),
  R(320, 13, 42, 12, 3, ["breakfast", "snack"],
    { name: "Peanut butter banana smoothie", ingredients: ["1 banana", "250 ml milk", "1 tbsp peanut butter", "a few ice cubes"], steps: "Blend everything until smooth." },
    { name: "Banánové smoothie s arašidovým maslom", ingredients: ["1 banán", "250 ml mlieka", "1 lyžica arašidového masla", "pár kociek ľadu"], steps: "Všetko rozmixuj dohladka." }),
  R(150, 6, 20, 6, 3, ["snack"],
    { name: "Hummus with carrot sticks", ingredients: ["4 tbsp hummus", "2 carrots"], steps: "Cut the carrots into sticks and dip them in the hummus." },
    { name: "Hummus s mrkvou", ingredients: ["4 lyžice hummusu", "2 mrkvy"], steps: "Mrkvu nakrájaj na tyčinky a namáčaj do hummusu." }),
  R(480, 22, 57, 16, 10, ["lunch", "dinner"],
    { name: "Egg fried rice", ingredients: ["1 cup cooked rice", "2 eggs", "handful of frozen peas", "1 tsp oil", "soy sauce"], steps: "Fry the peas in oil for 2 min and add the rice. Push it aside, scramble the eggs in the pan, then mix everything with soy sauce." },
    { name: "Vyprážaná ryža s vajcom", ingredients: ["1 hrnček varenej ryže", "2 vajcia", "hrsť mrazeného hrášku", "1 lyžička oleja", "sójová omáčka"], steps: "Na oleji opeč hrášok 2 min, pridaj ryžu, odsuň nabok, na panvici urob praženicu a všetko premiešaj so sójovou omáčkou." }),
  R(430, 31, 40, 16, 15, ["dinner"],
    { name: "Salmon with microwaved veg", ingredients: ["120 g salmon fillet", "1 cup broccoli", "1 small potato", "lemon, salt"], steps: "Pan-fry the salmon for 4 min on each side. Microwave the broccoli and diced potato with a splash of water for 5–6 min." },
    { name: "Losos so zeleninou", ingredients: ["120 g filet z lososa", "hrnček brokolice", "1 malý zemiak", "citrón, soľ"], steps: "Lososa opeč 4 min z každej strany. Brokolicu a nakrájaný zemiak daj s trochou vody do mikrovlnky na 5–6 min." }),
  R(225, 9, 39, 4, 1, ["snack", "breakfast"],
    { name: "Glass of milk & a banana", ingredients: ["250 ml milk", "1 banana"], steps: "Pour, peel, enjoy." },
    { name: "Pohár mlieka a banán", ingredients: ["250 ml mlieka", "1 banán"], steps: "Nalej, ošúp, hotovo." }),
  R(400, 20, 37, 19, 6, ["lunch", "dinner", "snack"],
    { name: "Quesadilla", ingredients: ["1 tortilla wrap", "50 g grated cheese", "2 tbsp beans or ham", "salsa"], steps: "Put the cheese and filling on half of the wrap and fold it. Dry-fry for 2 min per side until the cheese melts." },
    { name: "Quesadilla", ingredients: ["1 tortilla", "50 g strúhaného syra", "2 lyžice fazule alebo šunky", "salsa"], steps: "Na polovicu tortilly daj syr a plnku, prelož a opeč nasucho 2 min z každej strany, kým sa syr neroztopí." }),
  R(300, 6, 12, 27, 1, ["snack"],
    { name: "Walnuts & dark chocolate", ingredients: ["28 g walnuts", "2 squares dark chocolate"], steps: "Grab and enjoy." },
    { name: "Orechy a horká čokoláda", ingredients: ["hrsť vlašských orechov (28 g)", "2 kocky horkej čokolády"], steps: "Hotovo, len si daj." }),
  R(170, 8, 9, 10, 10, ["lunch", "dinner", "snack"],
    { name: "Tomato & cucumber salad with egg", ingredients: ["1 tomato", "1/2 cucumber", "1 boiled egg", "1 tsp olive oil"], steps: "Chop the veg, slice the egg on top, drizzle with oil and season." },
    { name: "Paradajkovo-uhorkový šalát s vajcom", ingredients: ["1 paradajka", "1/2 uhorky", "1 vajce natvrdo", "1 lyžička olivového oleja"], steps: "Nakrájaj zeleninu, navrch daj nakrájané vajce, pokvapkaj olejom a dochuť." }),
  R(390, 37, 34, 10, 12, ["lunch", "dinner"],
    { name: "Chicken wrap", ingredients: ["1 tortilla wrap", "100 g chicken breast", "lettuce, tomato", "1 tbsp yogurt sauce"], steps: "Pan-fry sliced chicken for 6–8 min. Fill the wrap with the chicken, veg and sauce, then roll it up." },
    { name: "Kuracia tortilla", ingredients: ["1 tortilla", "100 g kuracích pŕs", "šalát, paradajka", "1 lyžica jogurtového dresingu"], steps: "Kuracie nakrájaj a opeč 6–8 min, daj do tortilly so zeleninou a dresingom a zaroluj." }),
  R(255, 11, 24, 12, 3, ["breakfast", "snack"],
    { name: "Bread with bryndza spread", ingredients: ["1 slice bread", "50 g bryndza", "1/2 onion or chives", "pinch of paprika"], steps: "Mix the bryndza with chopped onion and paprika and spread it on the bread." },
    { name: "Chlieb s bryndzovou nátierkou", ingredients: ["1 krajec chleba", "50 g bryndze", "1/2 cibule alebo pažítka", "štipka papriky"], steps: "Bryndzu zmiešaj s nakrájanou cibuľkou a paprikou a natri na chlieb." }),
  R(210, 20, 27, 2, 2, ["breakfast", "snack"],
    { name: "Skyr with oats & berries", ingredients: ["150 g skyr", "2 tbsp oats", "a handful of berries"], steps: "Put the skyr in a bowl and top with oats and berries." },
    { name: "Skyr s vločkami a ovocím", ingredients: ["150 g skyru", "2 lyžice ovsených vločiek", "hrsť bobuľového ovocia"], steps: "Skyr daj do misky a navrch pridaj vločky a ovocie." }),
  R(230, 26, 19, 6, 3, ["breakfast", "snack"],
    { name: "Quark with strawberries & honey", ingredients: ["150 g quark (tvaroh)", "100 g strawberries", "1 tsp honey", "splash of milk"], steps: "Stir the quark with a splash of milk until creamy, add chopped strawberries and honey." },
    { name: "Tvaroh s jahodami a medom", ingredients: ["150 g tvarohu", "100 g jahôd", "1 lyžička medu", "trochu mlieka"], steps: "Tvaroh vymiešaj s trochou mlieka dokrémova, pridaj nakrájané jahody a med." }),
  R(230, 35, 15, 4, 4, ["lunch", "dinner", "snack"],
    { name: "Tuna & corn salad", ingredients: ["1 can tuna in water", "3 tbsp sweet corn", "2 tbsp plain yogurt", "salt, pepper"], steps: "Drain the tuna and mix it with the corn and yogurt. Season. Eat as is or on bread." },
    { name: "Tuniakový šalát s kukuricou", ingredients: ["1 konzerva tuniaka vo vlastnej šťave", "3 lyžice kukurice", "2 lyžice bieleho jogurtu", "soľ, korenie"], steps: "Tuniaka sceď, zmiešaj s kukuricou a jogurtom, dochuť. Jedz samotné alebo na chlebe." }),
  R(285, 33, 6, 14, 12, ["lunch", "dinner"],
    { name: "Chicken salad", ingredients: ["100 g chicken breast", "1 bowl mixed salad", "2 tsp olive oil", "lemon, salt"], steps: "Pan-fry the chicken strips for 6–8 min, put them on the salad and drizzle with oil and lemon." },
    { name: "Šalát s kuracím mäsom", ingredients: ["100 g kuracích pŕs", "miska zeleninového šalátu", "2 lyžičky olivového oleja", "citrón, soľ"], steps: "Kuracie pásiky opeč 6–8 min, daj na šalát a pokvapkaj olejom a citrónom." }),
  R(340, 32, 42, 6, 2, ["breakfast", "snack"],
    { name: "Protein shake with banana", ingredients: ["1 scoop protein powder (30 g)", "250 ml milk", "1 banana"], steps: "Blend or shake everything together." },
    { name: "Proteínový nápoj s banánom", ingredients: ["1 odmerka proteínu (30 g)", "250 ml mlieka", "1 banán"], steps: "Všetko rozmixuj alebo pretrep v šejkri." }),
];
