// Common foods with typical portion sizes. Calories are approximate.
const FOODS = [
  // Fruit
  { name: "Apple", portion: "1 medium (180 g)", kcal: 95 },
  { name: "Banana", portion: "1 medium (120 g)", kcal: 105 },
  { name: "Orange", portion: "1 medium (130 g)", kcal: 62 },
  { name: "Grapes", portion: "1 cup (150 g)", kcal: 104 },
  { name: "Strawberries", portion: "1 cup (150 g)", kcal: 48 },
  { name: "Blueberries", portion: "1 cup (150 g)", kcal: 85 },
  { name: "Pear", portion: "1 medium (180 g)", kcal: 101 },
  { name: "Avocado", portion: "1/2 fruit (100 g)", kcal: 160 },
  // Vegetables
  { name: "Carrot", portion: "1 medium (60 g)", kcal: 25 },
  { name: "Cucumber", portion: "1 cup sliced", kcal: 16 },
  { name: "Tomato", portion: "1 medium", kcal: 22 },
  { name: "Broccoli (cooked)", portion: "1 cup", kcal: 55 },
  { name: "Mixed salad", portion: "1 bowl, no dressing", kcal: 35 },
  { name: "Potato (boiled)", portion: "1 medium (170 g)", kcal: 145 },
  { name: "Sweet potato (baked)", portion: "1 medium (150 g)", kcal: 135 },
  // Dairy & eggs
  { name: "Egg (boiled)", portion: "1 large", kcal: 78 },
  { name: "Egg (fried)", portion: "1 large", kcal: 90 },
  { name: "Milk (semi-skimmed)", portion: "1 glass (250 ml)", kcal: 125 },
  { name: "Greek yogurt (plain)", portion: "150 g", kcal: 146 },
  { name: "Yogurt (fruit)", portion: "150 g", kcal: 140 },
  { name: "Cottage cheese", portion: "100 g", kcal: 98 },
  { name: "Cheese (cheddar/edam)", portion: "1 slice (30 g)", kcal: 110 },
  { name: "Mozzarella", portion: "50 g", kcal: 140 },
  { name: "Butter", portion: "1 tbsp (14 g)", kcal: 100 },
  // Bread, grains
  { name: "Bread (white)", portion: "1 slice", kcal: 80 },
  { name: "Bread (wholegrain)", portion: "1 slice", kcal: 90 },
  { name: "Bread roll", portion: "1 roll", kcal: 150 },
  { name: "Oats (dry)", portion: "40 g", kcal: 150 },
  { name: "Rice (cooked)", portion: "1 cup (160 g)", kcal: 205 },
  { name: "Pasta (cooked)", portion: "1 cup (140 g)", kcal: 220 },
  { name: "Cornflakes", portion: "30 g", kcal: 113 },
  { name: "Tortilla wrap", portion: "1 medium", kcal: 140 },
  // Protein
  { name: "Chicken breast (cooked)", portion: "100 g", kcal: 165 },
  { name: "Ham", portion: "2 slices (30 g)", kcal: 45 },
  { name: "Tuna (canned in water)", portion: "1 can (120 g)", kcal: 130 },
  { name: "Salmon (cooked)", portion: "100 g", kcal: 208 },
  { name: "Minced beef (cooked)", portion: "100 g", kcal: 250 },
  { name: "Sausage", portion: "1 piece (50 g)", kcal: 150 },
  { name: "Beans (canned)", portion: "1/2 can (200 g)", kcal: 160 },
  { name: "Tofu", portion: "100 g", kcal: 76 },
  // Spreads, nuts, snacks
  { name: "Peanut butter", portion: "1 tbsp (16 g)", kcal: 95 },
  { name: "Honey", portion: "1 tsp", kcal: 21 },
  { name: "Jam", portion: "1 tbsp", kcal: 50 },
  { name: "Almonds", portion: "a handful (28 g)", kcal: 164 },
  { name: "Walnuts", portion: "a handful (28 g)", kcal: 185 },
  { name: "Dark chocolate", portion: "2 squares (20 g)", kcal: 110 },
  { name: "Milk chocolate", portion: "1 bar (45 g)", kcal: 240 },
  { name: "Potato chips", portion: "small bag (30 g)", kcal: 160 },
  { name: "Cookie", portion: "1 cookie", kcal: 75 },
  { name: "Granola bar", portion: "1 bar", kcal: 120 },
  { name: "Olive oil", portion: "1 tbsp", kcal: 120 },
  // Drinks
  { name: "Coffee (black)", portion: "1 cup", kcal: 2 },
  { name: "Coffee with milk", portion: "1 cup", kcal: 40 },
  { name: "Cappuccino", portion: "1 cup", kcal: 110 },
  { name: "Orange juice", portion: "1 glass (250 ml)", kcal: 112 },
  { name: "Cola", portion: "1 can (330 ml)", kcal: 139 },
  { name: "Beer", portion: "0.5 l", kcal: 215 },
  { name: "Wine", portion: "1 glass (150 ml)", kcal: 125 },
  // Common meals
  { name: "Pizza", portion: "1 slice", kcal: 285 },
  { name: "Burger", portion: "1 regular", kcal: 350 },
  { name: "French fries", portion: "medium portion", kcal: 365 },
  { name: "Soup (vegetable)", portion: "1 bowl", kcal: 120 },
  { name: "Schnitzel (breaded)", portion: "1 piece (150 g)", kcal: 400 },
  { name: "Spaghetti bolognese", portion: "1 plate", kcal: 550 },
];

// Very easy recipes, used for recommendations when you still have calories left.
// meals: which parts of the day the recipe suits.
const RECIPES = [
  { name: "Banana & peanut butter toast", kcal: 330, mins: 3, meals: ["breakfast", "snack"],
    ingredients: ["1 slice wholegrain bread", "1 tbsp peanut butter", "1 banana"],
    steps: "Toast the bread, spread peanut butter, top with banana slices." },
  { name: "Greek yogurt with honey & berries", kcal: 230, mins: 2, meals: ["breakfast", "snack"],
    ingredients: ["150 g Greek yogurt", "1/2 cup berries", "1 tsp honey"],
    steps: "Put yogurt in a bowl, add berries and drizzle with honey." },
  { name: "Overnight oats", kcal: 380, mins: 5, meals: ["breakfast"],
    ingredients: ["40 g oats", "150 ml milk", "1/2 banana", "1 tsp honey"],
    steps: "Mix oats and milk in a jar, leave in the fridge overnight. Top with banana and honey." },
  { name: "Scrambled eggs on toast", kcal: 350, mins: 7, meals: ["breakfast", "lunch", "dinner"],
    ingredients: ["2 eggs", "1 tsp butter", "1 slice bread", "pinch of salt"],
    steps: "Whisk eggs, cook in butter on low heat while stirring, serve on toast." },
  { name: "Two boiled eggs", kcal: 156, mins: 10, meals: ["breakfast", "snack"],
    ingredients: ["2 eggs", "salt, pepper"],
    steps: "Boil eggs for 8–10 minutes, cool in cold water, peel and season." },
  { name: "Apple with a handful of almonds", kcal: 260, mins: 1, meals: ["snack"],
    ingredients: ["1 apple", "28 g almonds"],
    steps: "Slice the apple and eat with the almonds." },
  { name: "Cottage cheese & cucumber", kcal: 140, mins: 2, meals: ["snack", "breakfast"],
    ingredients: ["125 g cottage cheese", "1/2 cucumber", "salt, pepper, chives"],
    steps: "Chop cucumber, mix with cottage cheese, season." },
  { name: "Ham & cheese sandwich", kcal: 330, mins: 3, meals: ["breakfast", "lunch", "snack"],
    ingredients: ["2 slices bread", "2 slices ham", "1 slice cheese", "a few lettuce leaves"],
    steps: "Put ham, cheese and lettuce between the bread slices." },
  { name: "Tuna wrap", kcal: 380, mins: 5, meals: ["lunch", "dinner"],
    ingredients: ["1 tortilla wrap", "1 can tuna", "1 tbsp light mayo or yogurt", "lettuce, tomato"],
    steps: "Mix tuna with mayo/yogurt, spread on the wrap, add veg and roll up." },
  { name: "Tuna pasta", kcal: 520, mins: 12, meals: ["lunch", "dinner"],
    ingredients: ["80 g dry pasta", "1 can tuna", "3 tbsp tomato sauce or passata", "pinch of oregano"],
    steps: "Cook pasta, drain, stir in tuna and tomato sauce, heat 1 minute." },
  { name: "Chicken & rice bowl", kcal: 480, mins: 15, meals: ["lunch", "dinner"],
    ingredients: ["120 g chicken breast", "1 cup cooked rice", "handful of frozen veg", "1 tsp soy sauce"],
    steps: "Cut chicken into strips and pan-fry 6–8 min, add frozen veg for 3 min, serve over rice with soy sauce." },
  { name: "Microwave jacket potato with beans", kcal: 330, mins: 10, meals: ["lunch", "dinner"],
    ingredients: ["1 medium potato", "1/2 can baked beans", "a little grated cheese (optional)"],
    steps: "Prick the potato, microwave 7–8 min turning once. Split it, top with warm beans (and cheese)." },
  { name: "Cheese omelette", kcal: 300, mins: 6, meals: ["breakfast", "lunch", "dinner"],
    ingredients: ["2 eggs", "30 g grated cheese", "1 tsp butter"],
    steps: "Whisk eggs, pour into buttered pan, sprinkle cheese, fold when set." },
  { name: "Caprese salad", kcal: 260, mins: 4, meals: ["lunch", "dinner", "snack"],
    ingredients: ["2 tomatoes", "60 g mozzarella", "1 tsp olive oil", "basil, salt"],
    steps: "Slice tomatoes and mozzarella, layer them, drizzle oil and season." },
  { name: "Quick bean & veg soup", kcal: 280, mins: 12, meals: ["lunch", "dinner"],
    ingredients: ["1/2 can mixed beans", "1 cup frozen veg", "400 ml stock (cube)", "pinch of paprika"],
    steps: "Put everything in a pot, simmer 10 minutes. Blend a little if you like it thicker." },
  { name: "Peanut butter banana smoothie", kcal: 390, mins: 3, meals: ["breakfast", "snack"],
    ingredients: ["1 banana", "250 ml milk", "1 tbsp peanut butter", "a few ice cubes"],
    steps: "Blend everything until smooth." },
  { name: "Hummus with carrot sticks", kcal: 180, mins: 3, meals: ["snack"],
    ingredients: ["4 tbsp hummus", "2 carrots"],
    steps: "Cut carrots into sticks and dip into hummus." },
  { name: "Egg fried rice", kcal: 450, mins: 10, meals: ["lunch", "dinner"],
    ingredients: ["1 cup cooked rice", "2 eggs", "handful of frozen peas", "1 tsp oil", "soy sauce"],
    steps: "Fry peas in oil 2 min, add rice, push aside, scramble eggs in the pan, mix everything with soy sauce." },
  { name: "Salmon with microwaved veg", kcal: 420, mins: 15, meals: ["dinner"],
    ingredients: ["120 g salmon fillet", "1 cup broccoli", "1 small potato", "lemon, salt"],
    steps: "Pan-fry salmon 4 min each side. Microwave broccoli and diced potato with a splash of water 5–6 min." },
  { name: "Glass of milk & a banana", kcal: 230, mins: 1, meals: ["snack", "breakfast"],
    ingredients: ["250 ml milk", "1 banana"],
    steps: "Pour, peel, enjoy." },
  { name: "Quesadilla", kcal: 420, mins: 6, meals: ["lunch", "dinner", "snack"],
    ingredients: ["1 tortilla wrap", "50 g grated cheese", "2 tbsp beans or ham", "salsa"],
    steps: "Put cheese and filling on half the wrap, fold, dry-fry 2 min per side until the cheese melts." },
  { name: "Handful of walnuts & dark chocolate", kcal: 295, mins: 1, meals: ["snack"],
    ingredients: ["28 g walnuts", "2 squares dark chocolate"],
    steps: "Grab and enjoy." },
  { name: "Tomato & cucumber salad with egg", kcal: 190, mins: 10, meals: ["lunch", "dinner", "snack"],
    ingredients: ["1 tomato", "1/2 cucumber", "1 boiled egg", "1 tsp olive oil"],
    steps: "Chop the veg, slice the egg on top, drizzle oil, season." },
  { name: "Chicken wrap", kcal: 450, mins: 12, meals: ["lunch", "dinner"],
    ingredients: ["1 tortilla wrap", "100 g chicken breast", "lettuce, tomato", "1 tbsp yogurt sauce"],
    steps: "Pan-fry sliced chicken 6–8 min, fill the wrap with chicken, veg and sauce, roll it up." },
];
