// Common foods with typical portions. Calories are approximate.
// F(en, sk, portion EN, portion SK, grams per portion, kcal per portion, extra search words)
// Extra words include Slovak/English variants and plural forms so descriptions like
// "2 rožky s maslom" or "two bananas" can be matched.
function F(en, sk, pEn, pSk, g, kcal, aliases) {
  return { name: { en, sk }, portion: { en: pEn, sk: pSk }, g, kcal, aliases: aliases || "" };
}

const FOODS = [
  // Fruit / Ovocie
  F("Apple", "Jablko", "1 medium", "1 stredné", 180, 95, "apples jablka jablk"),
  F("Banana", "Banán", "1 medium", "1 stredný", 120, 105, "bananas banany banan"),
  F("Orange", "Pomaranč", "1 medium", "1 stredný", 130, 62, "oranges pomarance"),
  F("Mandarin", "Mandarínka", "1 piece", "1 kus", 75, 40, "mandarins tangerine mandarinky"),
  F("Grapes", "Hrozno", "1 cup", "1 hrnček", 150, 104, "grape"),
  F("Strawberries", "Jahody", "1 cup", "1 hrnček", 150, 48, "strawberry jahoda"),
  F("Blueberries", "Čučoriedky", "1 cup", "1 hrnček", 150, 85, "blueberry cucoriedka"),
  F("Pear", "Hruška", "1 medium", "1 stredná", 180, 101, "pears hrusky"),
  F("Peach", "Broskyňa", "1 medium", "1 stredná", 150, 58, "peaches broskyne"),
  F("Plums", "Slivky", "3 pieces", "3 kusy", 200, 90, "plum slivka"),
  F("Watermelon", "Melón (vodový)", "1 slice", "1 plátok", 280, 85, "melon melona dyna"),
  F("Kiwi", "Kiwi", "1 piece", "1 kus", 75, 42, "kiwis"),
  F("Avocado", "Avokádo", "1/2 fruit", "1/2 plodu", 100, 160, "avocados"),
  // Vegetables / Zelenina
  F("Carrot", "Mrkva", "1 medium", "1 stredná", 60, 25, "carrots mrkvy"),
  F("Cucumber", "Uhorka", "1/2 cucumber", "1/2 uhorky", 150, 23, "cucumbers uhorky uhorku"),
  F("Tomato", "Paradajka", "1 medium", "1 stredná", 120, 22, "tomatoes paradajky"),
  F("Bell pepper", "Paprika", "1 medium", "1 stredná", 120, 31, "pepper papriky"),
  F("Broccoli (cooked)", "Brokolica (varená)", "1 cup", "1 hrnček", 150, 55, "brokolicu"),
  F("Mixed salad", "Zeleninový šalát", "1 bowl, no dressing", "1 miska, bez dresingu", 150, 35, "salad salat"),
  F("Potatoes (boiled)", "Zemiaky (varené)", "1 medium", "1 stredný", 170, 145, "potato zemiak zemiakov"),
  F("Mashed potatoes", "Zemiaková kaša", "1 portion", "1 porcia", 200, 210, "puree pure kasa"),
  F("Sweet potato (baked)", "Batáty (pečené)", "1 medium", "1 stredný", 150, 135, "batat"),
  F("Sauerkraut", "Kyslá kapusta", "1 portion", "1 porcia", 150, 30, "kapusta"),
  // Dairy & eggs / Mliečne a vajcia
  F("Egg", "Vajce", "1 large", "1 veľké", 55, 78, "eggs vajcia vajec vajicko boiled varene"),
  F("Fried egg", "Volské oko", "1 egg", "1 vajce", 55, 90, "volske fried eggs"),
  F("Scrambled eggs", "Praženica", "from 2 eggs", "z 2 vajec", 120, 200, "prazenica prazenicu scrambled"),
  F("Milk", "Mlieko", "1 glass (250 ml)", "1 pohár (250 ml)", 250, 125, "mlieka"),
  F("Greek yogurt (plain)", "Grécky jogurt (biely)", "150 g", "150 g", 150, 146, "grecky"),
  F("Yogurt (fruit)", "Ovocný jogurt", "1 cup", "1 kelímok", 150, 140, "yogurt yoghurt jogurt jogurtu"),
  F("Kefir", "Kefír", "1 bottle (250 ml)", "1 fľaša (250 ml)", 250, 130, "acidko"),
  F("Cottage cheese", "Cottage / tvaroh", "100 g", "100 g", 100, 98, "tvaroh tvarohu cottage"),
  F("Cheese", "Syr", "1 slice", "1 plátok", 30, 110, "cheddar edam eidam gouda syra syrom"),
  F("Mozzarella", "Mozzarella", "50 g", "50 g", 50, 140, "mozarela"),
  F("Bryndza", "Bryndza", "50 g", "50 g", 50, 135, "bryndzou"),
  F("Butter", "Maslo", "1 tbsp", "1 lyžica", 14, 100, "maslom masla"),
  F("Cream cheese spread", "Nátierka / Lučina", "1 tbsp", "1 lyžica", 20, 50, "lucina natierka"),
  // Bread & grains / Pečivo a obilniny
  F("Bread (white)", "Chlieb", "1 slice", "1 krajec", 30, 80, "bread chleba chlebik krajec krajce"),
  F("Wholegrain bread", "Celozrnný chlieb", "1 slice", "1 krajec", 35, 90, "celozrnny wholemeal"),
  F("Bread roll (rožok)", "Rožok", "1 piece", "1 kus", 45, 125, "rozky rozkov roll rolls"),
  F("Bun / kaiser roll", "Žemľa", "1 piece", "1 kus", 55, 150, "zemle zemla bun"),
  F("Croissant", "Croissant", "1 piece", "1 kus", 60, 250, "kroasan croissanty"),
  F("Oats", "Ovsené vločky", "40 g dry", "40 g suché", 40, 150, "oatmeal vlocky ovsene porridge kasa"),
  F("Rice (cooked)", "Ryža (varená)", "1 cup", "1 hrnček", 160, 205, "ryza ryze ryzou"),
  F("Pasta (cooked)", "Cestoviny (varené)", "1 plate", "1 tanier", 200, 315, "cestovin spaghetti spagety penne noodles"),
  F("Cornflakes", "Cornflakes", "30 g", "30 g", 30, 113, "cereal cerealie lupienky"),
  F("Granola / muesli", "Müsli", "50 g", "50 g", 50, 220, "musli muesli granola"),
  F("Tortilla wrap", "Tortilla", "1 medium", "1 stredná", 60, 180, "wrap tortilly"),
  F("Pancake", "Palacinka", "1 piece", "1 kus", 70, 150, "pancakes palacinky"),
  // Meat & fish / Mäso a ryby
  F("Chicken breast (cooked)", "Kuracie prsia", "1 portion", "1 porcia", 150, 250, "chicken kuracie kura kuraci prsia"),
  F("Ham", "Šunka", "2 slices", "2 plátky", 30, 45, "sunka sunkou sunky"),
  F("Salami", "Saláma", "3 slices", "3 plátky", 30, 125, "salama salamy salami"),
  F("Sausage (frankfurter)", "Párky", "1 pair", "1 pár", 100, 280, "parky parok sausage hot dog"),
  F("Klobása", "Klobása", "1 piece", "1 kus", 100, 330, "klobasa klobasu"),
  F("Tuna (canned)", "Tuniak (konzerva)", "1 can", "1 konzerva", 120, 130, "tuniak tuniaka tuna"),
  F("Salmon", "Losos", "1 fillet", "1 filet", 125, 260, "losos lososa"),
  F("Pork chop", "Bravčové mäso", "1 portion", "1 porcia", 150, 350, "pork bravcove karé"),
  F("Beef", "Hovädzie mäso", "1 portion", "1 porcia", 150, 375, "beef hovadzie steak"),
  F("Schnitzel (breaded)", "Vyprážaný rezeň", "1 piece", "1 kus", 150, 400, "rezen schnitzel vyprazany"),
  F("Beans (canned)", "Fazuľa (konzerva)", "1/2 can", "1/2 konzervy", 200, 160, "beans fazula"),
  F("Tofu", "Tofu", "100 g", "100 g", 100, 76, ""),
  // Spreads, nuts, sweets / Nátierky, orechy, sladkosti
  F("Peanut butter", "Arašidové maslo", "1 tbsp", "1 lyžica", 16, 95, "arasidove"),
  F("Nutella", "Nutella", "1 tbsp", "1 lyžica", 20, 108, "nutelou"),
  F("Honey", "Med", "1 tsp", "1 lyžička", 7, 21, "medom"),
  F("Jam", "Džem", "1 tbsp", "1 lyžica", 20, 50, "dzem lekvar dzemom"),
  F("Almonds", "Mandle", "a handful", "hrsť", 28, 164, "almond mandli"),
  F("Walnuts", "Vlašské orechy", "a handful", "hrsť", 28, 185, "orechy orechov walnut nuts"),
  F("Peanuts", "Arašidy", "a handful", "hrsť", 28, 165, "arasidy peanut"),
  F("Dark chocolate", "Horká čokoláda", "2 squares", "2 kocky", 20, 110, "horka"),
  F("Milk chocolate", "Čokoláda", "1 bar (100 g)", "1 tabuľka (100 g)", 100, 535, "cokolada cokolady chocolate milka"),
  F("Chocolate bar (small)", "Čokoládová tyčinka", "1 bar", "1 tyčinka", 45, 230, "tycinka snickers mars twix kitkat"),
  F("Wafer (Horalky/Tatranka)", "Oblátka (Horalky/Tatranka)", "1 piece", "1 kus", 50, 265, "horalky horalka tatranka tatranky oblatka wafer"),
  F("Biscuits / cookies", "Sušienky / keksy", "3 pieces", "3 kusy", 30, 140, "susienky susienka keksy cookie cookies biscuits"),
  F("Chips", "Čipsy / chrumky", "small bag", "malé balenie", 30, 160, "cipsy crisps chrumky chips"),
  F("Granola bar", "Müsli tyčinka", "1 bar", "1 tyčinka", 25, 110, "musli tycinka protein bar"),
  F("Ice cream", "Zmrzlina", "2 scoops", "2 kopčeky", 100, 210, "zmrzliny icecream"),
  F("Cake", "Koláč / zákusok", "1 piece", "1 kus", 100, 350, "kolac zakusok torta cake buchta"),
  F("Donut", "Šiška / donut", "1 piece", "1 kus", 70, 270, "siska donut doughnut krapn"),
  F("Olive oil", "Olivový olej", "1 tbsp", "1 lyžica", 13, 120, "oil olej"),
  // Drinks / Nápoje
  F("Coffee (black)", "Káva (čierna)", "1 cup", "1 šálka", 200, 2, "coffee kava espresso"),
  F("Coffee with milk", "Káva s mliekom", "1 cup", "1 šálka", 200, 40, "latte kavu"),
  F("Cappuccino", "Cappuccino", "1 cup", "1 šálka", 200, 110, "kapucino"),
  F("Tea with sugar", "Čaj so cukrom", "1 cup", "1 šálka", 250, 35, "caj tea"),
  F("Orange juice", "Pomarančový džús", "1 glass", "1 pohár", 250, 112, "juice dzus"),
  F("Cola", "Kofola / cola", "1 can (330 ml)", "1 plechovka (330 ml)", 330, 139, "kofola coca pepsi soda limonada"),
  F("Beer", "Pivo", "0.5 l", "0,5 l", 500, 215, "piva beer"),
  F("Wine", "Víno", "1 glass (150 ml)", "1 pohár (150 ml)", 150, 125, "vino wine"),
  // Common meals / Bežné jedlá
  F("Pizza", "Pizza", "1 slice", "1 kúsok", 110, 285, "pizze"),
  F("Burger", "Burger", "1 regular", "1 bežný", 200, 500, "hamburger burgre"),
  F("French fries", "Hranolky", "medium portion", "stredná porcia", 120, 365, "hranolky hranoliek fries"),
  F("Soup", "Polievka", "1 bowl", "1 tanier", 300, 150, "polievka polievku soup"),
  F("Bryndzové halušky", "Bryndzové halušky", "1 plate", "1 tanier", 350, 700, "halusky halušky"),
  F("Goulash", "Guláš", "1 plate", "1 tanier", 300, 420, "gulas gulasu goulash"),
  F("Spaghetti bolognese", "Špagety bolonské", "1 plate", "1 tanier", 350, 550, "bolognese bolonske"),
  F("Fried cheese", "Vyprážaný syr", "1 piece", "1 kus", 120, 420, "vyprazany syr"),
  F("Kebab", "Kebab", "1 wrap", "1 kus", 350, 700, "gyros doner"),
  F("Sandwich", "Sendvič", "1 piece", "1 kus", 150, 330, "sendvic bageta baguette"),
];

// Very easy recipes, used for recommendations when you still have calories left.
// meals: which parts of the day the recipe suits.
function R(kcal, mins, meals, en, sk) { return { kcal, mins, meals, en, sk }; }

const RECIPES = [
  R(330, 3, ["breakfast", "snack"],
    { name: "Banana & peanut butter toast", ingredients: ["1 slice wholegrain bread", "1 tbsp peanut butter", "1 banana"], steps: "Toast the bread, spread peanut butter, top with banana slices." },
    { name: "Toast s arašidovým maslom a banánom", ingredients: ["1 krajec celozrnného chleba", "1 lyžica arašidového masla", "1 banán"], steps: "Opeč chlieb, natri arašidovým maslom a navrch daj plátky banánu." }),
  R(230, 2, ["breakfast", "snack"],
    { name: "Greek yogurt with honey & berries", ingredients: ["150 g Greek yogurt", "1/2 cup berries", "1 tsp honey"], steps: "Put yogurt in a bowl, add berries and drizzle with honey." },
    { name: "Grécky jogurt s medom a ovocím", ingredients: ["150 g gréckeho jogurtu", "hrsť bobuľového ovocia", "1 lyžička medu"], steps: "Daj jogurt do misky, pridaj ovocie a polej medom." }),
  R(380, 5, ["breakfast"],
    { name: "Overnight oats", ingredients: ["40 g oats", "150 ml milk", "1/2 banana", "1 tsp honey"], steps: "Mix oats and milk in a jar and leave in the fridge overnight. Top with banana and honey." },
    { name: "Ovsené vločky cez noc", ingredients: ["40 g ovsených vločiek", "150 ml mlieka", "1/2 banánu", "1 lyžička medu"], steps: "Zmiešaj vločky s mliekom v pohári a nechaj cez noc v chladničke. Navrch daj banán a med." }),
  R(350, 7, ["breakfast", "lunch", "dinner"],
    { name: "Scrambled eggs on toast", ingredients: ["2 eggs", "1 tsp butter", "1 slice bread", "pinch of salt"], steps: "Whisk the eggs and cook them in butter on low heat while stirring. Serve on toast." },
    { name: "Praženica na chlebe", ingredients: ["2 vajcia", "1 lyžička masla", "1 krajec chleba", "štipka soli"], steps: "Rozšľahaj vajcia, na masle ich pomaly miešaj na miernom ohni, podávaj na chlebe." }),
  R(156, 10, ["breakfast", "snack"],
    { name: "Two boiled eggs", ingredients: ["2 eggs", "salt, pepper"], steps: "Boil the eggs for 8–10 minutes, cool them in cold water, peel and season." },
    { name: "Dve vajcia natvrdo", ingredients: ["2 vajcia", "soľ, korenie"], steps: "Vajcia var 8–10 minút, schlaď v studenej vode, ošúp a okoreň." }),
  R(260, 1, ["snack"],
    { name: "Apple with a handful of almonds", ingredients: ["1 apple", "28 g almonds"], steps: "Slice the apple and eat it with the almonds." },
    { name: "Jablko s hrsťou mandlí", ingredients: ["1 jablko", "hrsť mandlí (28 g)"], steps: "Nakrájaj jablko a jedz s mandľami." }),
  R(170, 2, ["snack", "breakfast"],
    { name: "Cottage cheese & cucumber", ingredients: ["125 g cottage cheese", "1/2 cucumber", "salt, pepper, chives"], steps: "Chop the cucumber, mix it with the cottage cheese and season." },
    { name: "Cottage s uhorkou", ingredients: ["125 g cottage syra", "1/2 uhorky", "soľ, korenie, pažítka"], steps: "Nakrájaj uhorku, zmiešaj s cottage syrom a dochuť." }),
  R(330, 3, ["breakfast", "lunch", "snack"],
    { name: "Ham & cheese sandwich", ingredients: ["2 slices bread", "2 slices ham", "1 slice cheese", "a few lettuce leaves"], steps: "Put the ham, cheese and lettuce between the bread slices." },
    { name: "Chlieb so šunkou a syrom", ingredients: ["2 krajce chleba", "2 plátky šunky", "1 plátok syra", "pár listov šalátu"], steps: "Medzi krajce chleba daj šunku, syr a šalát." }),
  R(380, 5, ["lunch", "dinner"],
    { name: "Tuna wrap", ingredients: ["1 tortilla wrap", "1 can tuna", "1 tbsp light mayo or yogurt", "lettuce, tomato"], steps: "Mix the tuna with mayo or yogurt, spread it on the wrap, add the veg and roll it up." },
    { name: "Tortilla s tuniakom", ingredients: ["1 tortilla", "1 konzerva tuniaka", "1 lyžica jogurtu alebo light majonézy", "šalát, paradajka"], steps: "Zmiešaj tuniaka s jogurtom, natri na tortillu, pridaj zeleninu a zaroluj." }),
  R(520, 12, ["lunch", "dinner"],
    { name: "Tuna pasta", ingredients: ["80 g dry pasta", "1 can tuna", "3 tbsp tomato sauce", "pinch of oregano"], steps: "Cook the pasta and drain it. Stir in the tuna and tomato sauce and heat for 1 minute." },
    { name: "Cestoviny s tuniakom", ingredients: ["80 g suchých cestovín", "1 konzerva tuniaka", "3 lyžice paradajkovej omáčky", "štipka oregana"], steps: "Uvar cestoviny, sceď, vmiešaj tuniaka a omáčku, 1 minútu prehrej." }),
  R(480, 15, ["lunch", "dinner"],
    { name: "Chicken & rice bowl", ingredients: ["120 g chicken breast", "1 cup cooked rice", "handful of frozen veg", "1 tsp soy sauce"], steps: "Cut the chicken into strips and pan-fry for 6–8 min. Add the frozen veg for 3 min, then serve over rice with soy sauce." },
    { name: "Kuracie s ryžou", ingredients: ["120 g kuracích pŕs", "1 hrnček varenej ryže", "hrsť mrazenej zeleniny", "1 lyžička sójovej omáčky"], steps: "Kuracie nakrájaj na pásiky a opeč 6–8 min, pridaj zeleninu na 3 min, podávaj s ryžou a sójovou omáčkou." }),
  R(330, 10, ["lunch", "dinner"],
    { name: "Microwave jacket potato with beans", ingredients: ["1 medium potato", "1/2 can baked beans", "a little grated cheese (optional)"], steps: "Prick the potato and microwave it for 7–8 min, turning once. Split it and top with warm beans (and cheese)." },
    { name: "Zemiak z mikrovlnky s fazuľou", ingredients: ["1 stredný zemiak", "1/2 konzervy fazule v paradajkovej omáčke", "trochu syra (nepovinné)"], steps: "Zemiak popichaj a daj na 7–8 min do mikrovlnky (raz otoč). Rozkroj a navrch daj teplú fazuľu (a syr)." }),
  R(300, 6, ["breakfast", "lunch", "dinner"],
    { name: "Cheese omelette", ingredients: ["2 eggs", "30 g grated cheese", "1 tsp butter"], steps: "Whisk the eggs, pour them into a buttered pan, sprinkle the cheese and fold once set." },
    { name: "Syrová omeleta", ingredients: ["2 vajcia", "30 g strúhaného syra", "1 lyžička masla"], steps: "Rozšľahaj vajcia, vylej na panvicu s maslom, posyp syrom a keď stuhne, prelož." }),
  R(260, 4, ["lunch", "dinner", "snack"],
    { name: "Caprese salad", ingredients: ["2 tomatoes", "60 g mozzarella", "1 tsp olive oil", "basil, salt"], steps: "Slice the tomatoes and mozzarella, layer them, drizzle with oil and season." },
    { name: "Šalát caprese", ingredients: ["2 paradajky", "60 g mozzarelly", "1 lyžička olivového oleja", "bazalka, soľ"], steps: "Nakrájaj paradajky a mozzarellu, poukladaj, pokvapkaj olejom a osoľ." }),
  R(280, 12, ["lunch", "dinner"],
    { name: "Quick bean & veg soup", ingredients: ["1/2 can mixed beans", "1 cup frozen veg", "400 ml stock (cube)", "pinch of paprika"], steps: "Put everything in a pot and simmer for 10 minutes." },
    { name: "Rýchla fazuľová polievka", ingredients: ["1/2 konzervy fazule", "hrnček mrazenej zeleniny", "400 ml vývaru (z kocky)", "štipka papriky"], steps: "Všetko daj do hrnca a 10 minút povar." }),
  R(390, 3, ["breakfast", "snack"],
    { name: "Peanut butter banana smoothie", ingredients: ["1 banana", "250 ml milk", "1 tbsp peanut butter", "a few ice cubes"], steps: "Blend everything until smooth." },
    { name: "Banánové smoothie s arašidovým maslom", ingredients: ["1 banán", "250 ml mlieka", "1 lyžica arašidového masla", "pár kociek ľadu"], steps: "Všetko rozmixuj dohladka." }),
  R(180, 3, ["snack"],
    { name: "Hummus with carrot sticks", ingredients: ["4 tbsp hummus", "2 carrots"], steps: "Cut the carrots into sticks and dip them in the hummus." },
    { name: "Hummus s mrkvou", ingredients: ["4 lyžice hummusu", "2 mrkvy"], steps: "Mrkvu nakrájaj na tyčinky a namáčaj do hummusu." }),
  R(450, 10, ["lunch", "dinner"],
    { name: "Egg fried rice", ingredients: ["1 cup cooked rice", "2 eggs", "handful of frozen peas", "1 tsp oil", "soy sauce"], steps: "Fry the peas in oil for 2 min and add the rice. Push it aside, scramble the eggs in the pan, then mix everything with soy sauce." },
    { name: "Vyprážaná ryža s vajcom", ingredients: ["1 hrnček varenej ryže", "2 vajcia", "hrsť mrazeného hrášku", "1 lyžička oleja", "sójová omáčka"], steps: "Na oleji opeč hrášok 2 min, pridaj ryžu, odsuň nabok, na panvici urob praženicu a všetko premiešaj so sójovou omáčkou." }),
  R(420, 15, ["dinner"],
    { name: "Salmon with microwaved veg", ingredients: ["120 g salmon fillet", "1 cup broccoli", "1 small potato", "lemon, salt"], steps: "Pan-fry the salmon for 4 min on each side. Microwave the broccoli and diced potato with a splash of water for 5–6 min." },
    { name: "Losos so zeleninou", ingredients: ["120 g filet z lososa", "hrnček brokolice", "1 malý zemiak", "citrón, soľ"], steps: "Lososa opeč 4 min z každej strany. Brokolicu a nakrájaný zemiak daj s trochou vody do mikrovlnky na 5–6 min." }),
  R(230, 1, ["snack", "breakfast"],
    { name: "Glass of milk & a banana", ingredients: ["250 ml milk", "1 banana"], steps: "Pour, peel, enjoy." },
    { name: "Pohár mlieka a banán", ingredients: ["250 ml mlieka", "1 banán"], steps: "Nalej, ošúp, hotovo." }),
  R(420, 6, ["lunch", "dinner", "snack"],
    { name: "Quesadilla", ingredients: ["1 tortilla wrap", "50 g grated cheese", "2 tbsp beans or ham", "salsa"], steps: "Put the cheese and filling on half of the wrap and fold it. Dry-fry for 2 min per side until the cheese melts." },
    { name: "Quesadilla", ingredients: ["1 tortilla", "50 g strúhaného syra", "2 lyžice fazule alebo šunky", "salsa"], steps: "Na polovicu tortilly daj syr a plnku, prelož a opeč nasucho 2 min z každej strany, kým sa syr neroztopí." }),
  R(295, 1, ["snack"],
    { name: "Walnuts & dark chocolate", ingredients: ["28 g walnuts", "2 squares dark chocolate"], steps: "Grab and enjoy." },
    { name: "Orechy a horká čokoláda", ingredients: ["hrsť vlašských orechov (28 g)", "2 kocky horkej čokolády"], steps: "Hotovo, len si daj." }),
  R(190, 10, ["lunch", "dinner", "snack"],
    { name: "Tomato & cucumber salad with egg", ingredients: ["1 tomato", "1/2 cucumber", "1 boiled egg", "1 tsp olive oil"], steps: "Chop the veg, slice the egg on top, drizzle with oil and season." },
    { name: "Paradajkovo-uhorkový šalát s vajcom", ingredients: ["1 paradajka", "1/2 uhorky", "1 vajce natvrdo", "1 lyžička olivového oleja"], steps: "Nakrájaj zeleninu, navrch daj nakrájané vajce, pokvapkaj olejom a dochuť." }),
  R(450, 12, ["lunch", "dinner"],
    { name: "Chicken wrap", ingredients: ["1 tortilla wrap", "100 g chicken breast", "lettuce, tomato", "1 tbsp yogurt sauce"], steps: "Pan-fry sliced chicken for 6–8 min. Fill the wrap with the chicken, veg and sauce, then roll it up." },
    { name: "Kuracia tortilla", ingredients: ["1 tortilla", "100 g kuracích pŕs", "šalát, paradajka", "1 lyžica jogurtového dresingu"], steps: "Kuracie nakrájaj a opeč 6–8 min, daj do tortilly so zeleninou a dresingom a zaroluj." }),
  R(250, 3, ["breakfast", "snack"],
    { name: "Bread with bryndza spread", ingredients: ["1 slice bread", "50 g bryndza", "1/2 onion or chives", "pinch of paprika"], steps: "Mix the bryndza with chopped onion and paprika and spread it on the bread." },
    { name: "Chlieb s bryndzovou nátierkou", ingredients: ["1 krajec chleba", "50 g bryndze", "1/2 cibule alebo pažítka", "štipka papriky"], steps: "Bryndzu zmiešaj s nakrájanou cibuľkou a paprikou a natri na chlieb." }),
];
